### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by acesuares** [ties/logcheck-extrarules#10]
This is not an issue, but just a question... maybe you know the answer!

On my system, this line:
`Oct  8 06:15:33 server sshd[3905]: Connection closed by 127.0.0.1 port 34168 [preauth]`
is properly ignored by this rule:
`^\w{3} [ :0-9]{11} [._[:alnum:]-]+ sshd\[[0-9]+\]: Connection [a-z]+ by [.0-9]{7,15} \[preauth\]$`

But this line:
`Oct  1 08:38:33 server sshd[32531]: Connection reset by 127.0.0.1 port 51146 [preauth]`
is not filtered and it shows up in the report.

I can't find out why.

**Comment by ties** [comment]
That line looks strange. The regex expects two positions for the day of month:
```
Oct  7 09:38:47 host sshd[25269]: Connection reset by 123.183.209.140 port 51639 [preauth]
    ^^
```

In your example there is only one character there. Thus `[ :0-9]{11}` does not
match, it is 10 characters long.

This line should be matched by (including `port 51146`):
```
^\w{3} [ :0-9]{11} [._[:alnum:]-]+ sshd\[[0-9]+\]: (Connection reset by|Disconnected from) [[:alnum:].:]+ port [0-9]+(\s+\[preauth\])?$
```
and
```
^\w{3} [ :0-9]{11} [._[:alnum:]-]+ sshd\[[0-9]+\]: Connection closed by [[:alnum:].:]+ (port [0-9]+ )?\[preauth\]$
```
(And in both cases the '.' could be escaped)

Could you check if the line in your log has two positions for the day number?
And could you try to match it against the regexes that include a port number?

**Comment by acesuares** [comment]
Hi Ties,
Are you sure? The fist part of the regex (^\w{3} [ :0-9]{11} [._[:alnum:]-]+) is the same for all rules, since that is the format that syslog writes the logfiles in. 

And ` 7 09:38:47` is matched by `^\w{3} [ :0-9]{11}`: 
````
01     one space
02     one digit
03     one space
04-05  two digits
06     one colon
07-08  two digits
09     one colon
10-11  two digits
````

Furthermore,
`egrep ^\w{3} [ :0-9]{11} [._[:alnum:]-]+ sshd\[[0-9]+\]: Connection [a-z]+ by [.0-9]{7,15} \[preauth\]$ /var/log/auth.log`
does match. It just doesn't get filtered out by logcheck...

**Comment by ties** [comment]
The first part is the same for all rules.

However, when I copied the example you provided, it had one space (position 01  => 8). This seems to be happen when the markdown is rendered. Your line matches the prelude.

In any case, if the regex matches on the command line it should be filtered by logcheck.

This is quite confusing. Do you know if other rules from the same file are applied? And have you tried running logcheck in debug mode `sudo -u logcheck logcheck -d -t -o`?

**Comment by acesuares** [comment]
Somehow, the problem disappeared. It might have been a broken rules file. I am closing this...
